package com.lddev.scalefinder.model

import androidx.compose.ui.graphics.Color
import com.lddev.scalefinder.R

data class FretboardColors(
    val background: Color,
    val grainDark: Color,
    val grainLight: Color,
    val grainAlphaRange: ClosedFloatingPointRange<Float>,
    val edgeDarkenTop: Float,
    val edgeDarkenBottom: Float,
    val nutOutline: Color,
    val nutBody: Color,
    val nutHighlight: Color,
    val fretShadow: Color,
    val fretBody: Color,
    val fretHighlight: Color,
    val woundString: Color,
    val plainString: Color,
    val stringShadowAlpha: Float,
    val woundSpecularAlpha: Float,
    val plainSpecularAlpha: Float,
    val inlayShadowAlpha: Float,
    val inlayBody: Color,
    val inlayHighlightAlpha: Float,
    val noteNameColor: Color,
)

enum class FretboardTheme(val labelRes: Int, val colors: FretboardColors) {
    ROSEWOOD(
        R.string.fretboard_theme_rosewood,
        FretboardColors(
            background = Color(0xFF2E1B0E),
            grainDark = Color.Black,
            grainLight = Color(0xFF5D4037),
            grainAlphaRange = 0.02f..0.12f,
            edgeDarkenTop = 0.25f,
            edgeDarkenBottom = 0.20f,
            nutOutline = Color(0xFF303030),
            nutBody = Color(0xFFF0EBD8),
            nutHighlight = Color(0xFFFFF8EE),
            fretShadow = Color(0xFF505050),
            fretBody = Color(0xFFB0B0B0),
            fretHighlight = Color(0xFFE0E0E0),
            woundString = Color(0xFFB89B6C),
            plainString = Color(0xFFC8C8C8),
            stringShadowAlpha = 0.30f,
            woundSpecularAlpha = 0.18f,
            plainSpecularAlpha = 0.32f,
            inlayShadowAlpha = 0.40f,
            inlayBody = Color(0xFFF0ECE8),
            inlayHighlightAlpha = 0.50f,
            noteNameColor = Color(0xFFE0D0C0),
        ),
    ),

    MAPLE(
        R.string.fretboard_theme_maple,
        FretboardColors(
            background = Color(0xFFE8D5B0),
            grainDark = Color(0xFFB8956A),
            grainLight = Color(0xFFD4BA90),
            grainAlphaRange = 0.08f..0.20f,
            edgeDarkenTop = 0.10f,
            edgeDarkenBottom = 0.08f,
            nutOutline = Color(0xFF404040),
            nutBody = Color(0xFFF5F0E0),
            nutHighlight = Color(0xFFFFFDF5),
            fretShadow = Color(0xFF707070),
            fretBody = Color(0xFFA0A0A0),
            fretHighlight = Color(0xFFD0D0D0),
            woundString = Color(0xFFA08050),
            plainString = Color(0xFF909090),
            stringShadowAlpha = 0.20f,
            woundSpecularAlpha = 0.25f,
            plainSpecularAlpha = 0.40f,
            inlayShadowAlpha = 0.15f,
            inlayBody = Color(0xFF1A1A1A),
            inlayHighlightAlpha = 0.20f,
            noteNameColor = Color(0xFF3E2E1E),
        ),
    ),

    EBONY(
        R.string.fretboard_theme_ebony,
        FretboardColors(
            background = Color(0xFF151015),
            grainDark = Color.Black,
            grainLight = Color(0xFF2A2028),
            grainAlphaRange = 0.03f..0.10f,
            edgeDarkenTop = 0.15f,
            edgeDarkenBottom = 0.12f,
            nutOutline = Color(0xFF252525),
            nutBody = Color(0xFFE8E0D0),
            nutHighlight = Color(0xFFF5F0E8),
            fretShadow = Color(0xFF3A3A3A),
            fretBody = Color(0xFFC0C0C0),
            fretHighlight = Color(0xFFEAEAEA),
            woundString = Color(0xFFC0A878),
            plainString = Color(0xFFD0D0D0),
            stringShadowAlpha = 0.40f,
            woundSpecularAlpha = 0.22f,
            plainSpecularAlpha = 0.38f,
            inlayShadowAlpha = 0.50f,
            inlayBody = Color(0xFFF5F0EA),
            inlayHighlightAlpha = 0.60f,
            noteNameColor = Color(0xFFD0C8B8),
        ),
    ),

    MINIMAL(
        R.string.fretboard_theme_minimal,
        FretboardColors(
            background = Color(0xFF1E1E2E),
            grainDark = Color.Transparent,
            grainLight = Color.Transparent,
            grainAlphaRange = 0f..0f,
            edgeDarkenTop = 0f,
            edgeDarkenBottom = 0f,
            nutOutline = Color(0xFF404060),
            nutBody = Color(0xFFE0E0F0),
            nutHighlight = Color(0xFFF0F0FF),
            fretShadow = Color(0xFF3A3A50),
            fretBody = Color(0xFF606080),
            fretHighlight = Color(0xFF808098),
            woundString = Color(0xFF9090A8),
            plainString = Color(0xFFB0B0C0),
            stringShadowAlpha = 0.15f,
            woundSpecularAlpha = 0.12f,
            plainSpecularAlpha = 0.20f,
            inlayShadowAlpha = 0.20f,
            inlayBody = Color(0xFF505070),
            inlayHighlightAlpha = 0.30f,
            noteNameColor = Color(0xFFA0A0C0),
        ),
    ),
    ;

    companion object {
        fun all(): List<FretboardTheme> = entries.toList()
    }
}
